language: elixir

notifications:
  email: true

otp_release:
  - 18.0

elixir:
  - 1.1.1

before_install:
  - export MIX_ENV=test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - mix local.hex --force
  - mix do deps.get, deps.compile, webdriver.firefox.install

script: mix test
