language: elixir
elixir: 1.0.1
notifications:
  email: false
otp_release:
  - 17.0
env:
  - MIX_ENV=test
before_install:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
script: " mix do deps.get, deps.compile, webdriver.firefox.install, test"
